ESSArch_Core/auth/urls.py
from django.conf.urls import url
from rest_auth.views import (
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
    UserDetailsView,
)

from ESSArch_Core.auth.views import LoginView, LogoutView, login_services

urlpatterns = [
    # URLs that do not require a session or valid token
    url(r'^password/reset/$', PasswordResetView.as_view(),
        name='rest_password_reset'),
    url(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url(r'^login/$', LoginView.as_view(), name='rest_login'),
    url(r'^logout/$', LogoutView.as_view(), name='rest_logout'),
    url(r'^services/$', login_services, name='services'),
    url(r'^user/$', UserDetailsView.as_view(), name='rest_user_details'),
    url(r'^password/change/$', PasswordChangeView.as_view(),
        name='rest_password_change'),
]

ESSArch_Core/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from ESSArch_Core.agents.views import (
    AgentIdentifierTypeViewSet,
    AgentNameTypeViewSet,
    AgentNoteTypeViewSet,
    AgentPlaceTypeViewSet,
    AgentRelationTypeViewSet,
    AgentTagLinkRelationTypeViewSet,
    AgentTypeViewSet,
    AgentViewSet,
    AuthorityTypeViewSet,
    RefCodeViewSet,
)
from ESSArch_Core.api.views import LanguageViewSet
from ESSArch_Core.auth.views import (
    GroupViewSet,
    MeView,
    NotificationViewSet,
    OrganizationViewSet,
    PermissionViewSet,
    UserViewSet,
)
from ESSArch_Core.configuration.views import (
    EventTypeViewSet,
    ParameterViewSet,
    PathViewSet,
    SiteView,
    StoragePolicyViewSet,
    SysInfoView,
)
from ESSArch_Core.fixity.views import (
    ValidationFilesViewSet,
    ValidationViewSet,
    ValidatorViewSet,
    ValidatorWorkflowViewSet,
)
from ESSArch_Core.ip.views import (
    ConsignMethodViewSet,
    EventIPViewSet,
    InformationPackageReceptionViewSet,
    InformationPackageViewSet,
    OrderTypeViewSet,
    OrderViewSet,
    WorkareaEntryViewSet,
    WorkareaFilesViewSet,
    WorkareaViewSet,
)
from ESSArch_Core.maintenance.views import (
    AppraisalJobViewSet,
    AppraisalRuleViewSet,
    ConversionJobViewSet,
    ConversionRuleViewSet,
)
from ESSArch_Core.profiles.views import (
    InformationPackageProfileIPViewSet,
    ProfileIPDataTemplateViewSet,
    ProfileIPDataViewSet,
    ProfileIPViewSet,
    ProfileMakerExtensionViewSet,
    ProfileMakerTemplateViewSet,
    ProfileSAViewSet,
    ProfileViewSet,
    SubmissionAgreementIPDataViewSet,
    SubmissionAgreementTemplateView,
    SubmissionAgreementViewSet,
)
from ESSArch_Core.routers import ESSArchRouter
from ESSArch_Core.stats.views import export as export_stats, stats
from ESSArch_Core.storage.views import (
    IOQueueViewSet,
    RobotQueueViewSet,
    RobotViewSet,
    StorageMediumViewSet,
    StorageMethodTargetRelationViewSet,
    StorageMethodViewSet,
    StorageMigrationViewSet,
    StorageObjectViewSet,
    StorageTargetViewSet,
    TapeDriveViewSet,
    TapeSlotViewSet,
)
from ESSArch_Core.tags.search import ComponentSearchViewSet
from ESSArch_Core.tags.views import (
    ArchiveViewSet,
    DeliveryTypeViewSet,
    DeliveryViewSet,
    LocationFunctionTypeViewSet,
    LocationLevelTypeViewSet,
    LocationViewSet,
    MetricTypeViewSet,
    NodeIdentifierTypeViewSet,
    NodeNoteTypeViewSet,
    NodeRelationTypeViewSet,
    StoredSearchViewSet,
    StructureTypeViewSet,
    StructureUnitTypeViewSet,
    StructureUnitViewSet,
    StructureViewSet,
    TagInformationPackagesViewSet,
    TagVersionTypeViewSet,
    TagVersionViewSet,
    TagViewSet,
    TransferViewSet,
)
from ESSArch_Core.WorkflowEngine.views import (
    ProcessStepViewSet,
    ProcessTaskViewSet,
    ProcessViewSet,
)

admin.site.site_header = 'ESSArch Administration'
admin.site.site_title = 'ESSArch Administration'

router = ESSArchRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'agents', AgentViewSet).register(
    r'archives',
    ArchiveViewSet,
    basename='agent-archives',
    parents_query_lookups=['agent']
)
router.register(r'agent-types', AgentTypeViewSet)
router.register(r'agent-identifier-types', AgentIdentifierTypeViewSet)
router.register(r'agent-name-types', AgentNameTypeViewSet)
router.register(r'agent-note-types', AgentNoteTypeViewSet)
router.register(r'agent-place-types', AgentPlaceTypeViewSet)
router.register(r'agent-relation-types', AgentRelationTypeViewSet)
router.register(r'agent-tag-relation-types', AgentTagLinkRelationTypeViewSet)
router.register(r'authority-types', AuthorityTypeViewSet)
router.register(r'deliveries', DeliveryViewSet).register(
    r'transfers',
    TransferViewSet,
    basename='transfers',
    parents_query_lookups=['delivery']
)
router.register(r'deliveries', DeliveryViewSet).register(
    r'events',
    EventIPViewSet,
    basename='delivery-events',
    parents_query_lookups=['delivery'],
)
router.register(r'delivery-types', DeliveryTypeViewSet)
router.register(r'transfers', TransferViewSet).register(
    r'events',
    EventIPViewSet,
    basename='transfer-events',
    parents_query_lookups=['transfer'],
)
router.register(r'transfers', TransferViewSet).register(
    r'structure-units',
    StructureUnitViewSet,
    basename='transfer-structure-units',
    parents_query_lookups=['transfers'],
)
router.register(r'transfers', TransferViewSet).register(
    r'tags',
    TagVersionViewSet,
    basename='transfer-tags',
    parents_query_lookups=['transfers'],
)
router.register(r'structures', StructureViewSet).register(
    r'units',
    StructureUnitViewSet,
    basename='structure-units',
    parents_query_lookups=['structure']
)
router.register(r'structure-units', StructureUnitViewSet).register(
    r'transfers',
    TransferViewSet,
    basename='structure-unit-transfers',
    parents_query_lookups=['structure_units'],
)
router.register(r'structure-units', StructureUnitViewSet).register(
    r'deliveries',
    DeliveryViewSet,
    basename='structure-unit-deliveries',
    parents_query_lookups=['structure_units__delivery'],
)
router.register(r'structure-types', StructureTypeViewSet)
router.register(r'structure-unit-types', StructureUnitTypeViewSet)
router.register(r'node-relation-types', NodeRelationTypeViewSet)
router.register(r'node-identifier-types', NodeIdentifierTypeViewSet)
router.register(r'node-note-types', NodeNoteTypeViewSet)
router.register(r'locations', LocationViewSet).register(
    r'tags',
    TagVersionViewSet,
    basename='location-tags',
    parents_query_lookups=['location']
)
router.register(r'metric-types', MetricTypeViewSet)
router.register(r'location-level-types', LocationLevelTypeViewSet)
router.register(r'location-function-types', LocationFunctionTypeViewSet)
router.register(r'structure-units', StructureUnitViewSet)
router.register(r'tag-version-types', TagVersionTypeViewSet)

router.register(r'ref-codes', RefCodeViewSet)
router.register(r'languages', LanguageViewSet)
router.register(r'me/searches', StoredSearchViewSet)
router.register(r'permissions', PermissionViewSet)
router.register(r'profilemaker-extensions', ProfileMakerExtensionViewSet)
router.register(r'profilemaker-templates', ProfileMakerTemplateViewSet)
router.register(r'information-packages', InformationPackageViewSet, basename='informationpackage')
router.register(r'information-packages', InformationPackageViewSet).register(
    r'appraisal-rules',
    AppraisalRuleViewSet,
    basename='ip-appraisal-rules',
    parents_query_lookups=['information_packages']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'conversion-rules',
    ConversionRuleViewSet,
    basename='ip-conversion-rules',
    parents_query_lookups=['information_packages']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'events',
    EventIPViewSet,
    basename='ip-events',
    parents_query_lookups=['linkingObjectIdentifierValue']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'profiles',
    InformationPackageProfileIPViewSet,
    basename='ip-profiles',
    parents_query_lookups=['ip']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'storage-objects',
    StorageObjectViewSet,
    basename='ip-storage-objects',
    parents_query_lookups=['ip']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'storage-migration-targets',
    StorageTargetViewSet,
    basename='ip-storage-migration-targets',
    parents_query_lookups=['ip']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'validations',
    ValidationViewSet,
    basename='ip-validations',
    parents_query_lookups=['information_package']
)
router.register(r'information-packages', InformationPackageViewSet).register(
    r'validation-files',
    ValidationFilesViewSet,
    basename='ip-validation-files',
    parents_query_lookups=['information_package']
)

router.register(r'io-queue', IOQueueViewSet)

router.register(r'notifications', NotificationViewSet)
router.register(r'steps', ProcessStepViewSet)
router.register(r'steps', ProcessStepViewSet, basename='steps').register(
    r'tasks',
    ProcessTaskViewSet,
    basename='steps-tasks',
    parents_query_lookups=['processstep']
)
router.register(r'steps', ProcessStepViewSet, basename='steps').register(
    r'children',
    ProcessViewSet,
    basename='steps-children',
    parents_query_lookups=['processstep']
)

router.register(r'tags', TagViewSet)
router.register(r'tags', TagViewSet, basename='tags').register(
    r'information-packages',
    TagInformationPackagesViewSet,
    basename='tags-informationpackages',
    parents_query_lookups=['tag']
)
router.register(r'tags', TagViewSet, basename='tags').register(
    r'descendants',
    TagViewSet,
    basename='tags-descendants',
    parents_query_lookups=['tag']
)

router.register(r'tasks', ProcessTaskViewSet)
router.register(r'tasks', ProcessTaskViewSet).register(
    r'validations',
    ValidationViewSet,
    basename='task-validations',
    parents_query_lookups=['task']
)


router.register(r'organizations', OrganizationViewSet, basename='organizations')
router.register(r'appraisal-jobs', AppraisalJobViewSet)
router.register(r'appraisal-rules', AppraisalRuleViewSet)
router.register(r'conversion-jobs', ConversionJobViewSet)
router.register(r'conversion-rules', ConversionRuleViewSet)
router.register(r'validators', ValidatorViewSet, basename='validators')
router.register(r'validator-workflows', ValidatorWorkflowViewSet, basename='validator-workflows')
router.register(r'validations', ValidationViewSet)
router.register(r'events', EventIPViewSet)
router.register(r'event-types', EventTypeViewSet)

ESSArch_Core/essxml/ProfileMaker/urls.py
"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

from django.conf.urls import url

from . import views
from .views import add, addExtension, create, edit, generate, index

urlpatterns = [
    url(r'^$', index.as_view(), name='template_index'),
    url(r'^edit/(?P<name>[A-z0-9]+)/$', edit.as_view(), name='template_edit'),
    url(r'^add/$', add.as_view(), name='template_add'),
    url(r'^add-extension/(?P<name>[A-z0-9]+)/$', addExtension.as_view(), name='template_add_extension'),
    # url(r'^reset/$', views.resetData, name='reset_data_template'),
    url(r'^generate/(?P<name>[A-z0-9]+)/$', generate.as_view(), name='generate_template'),
    url(r'^delete/(?P<name>[A-z0-9]+)/$', views.deleteTemplate, name='delete_template'),
    url(
        r'^struct/addChild/(?P<name>[A-z0-9]+)/(?P<newElementName>[A-z0-9]+)/(?P<elementUuid>[A-z0-9-]+)/$',
        views.addChild, name='add_data_template'
    ),
    url(r'^struct/addUserChild/(?P<name>[A-z0-9]+)/$', views.addUserChild, name='add_userdata_template'),
    url(r'^struct/addExtensionChild/(?P<name>[A-z0-9]+)/$', views.addExtensionElement, name='add_userdata_template'),
    url(
        r'^struct/removeChild/(?P<name>[A-z0-9]+)/(?P<uuid>[A-z0-9-]+)/$',
        views.removeChild, name='remove_child_template'
    ),
    url(
        r'^struct/addAttrib/(?P<name>[A-z0-9]+)/(?P<uuid>[A-z0-9-]+)/$',
        views.addAttribute, name='add_attrib_template'
    ),
    url(r'^getAttributes/(?P<name>[A-z0-9]+)/$', views.getAttributes, name='add_attrib_template'),
    url(r'^getElements/(?P<name>[A-z0-9]+)/$', views.getElements, name='add_attrib_template'),

    url(
        r'^struct/setContainsFiles/(?P<name>[A-z0-9]+)/(?P<uuid>[A-z0-9-]+)/(?P<containsFiles>[0-1])/$',
        views.setContainsFiles, name='setContainsFiles_template'
    ),
    url(r'^struct/(?P<name>[A-z0-9]+)/$', views.getExistingElements, name='get_existing_elements'),
    url(r'^struct/elements/(?P<name>[A-z0-9-]+)/$', views.getAllElements, name='get_all_elements'),
    url(r'^make/$', create.as_view(), name='create_template'),
    # url(r'^edit/(?P<name>[A-z0-9-]+)/$', views.saveForm, name='update_template'),
    # url(r'^edit/$', edit.as_view(), name='edit_template'),
    # url(r'^submitipcreate/(?P<id>\d+)$', SubmitIPCreate.as_view(), name='submit_submitipcreate'),
]

ESSArch_Core/essxml/ProfileMaker/models.py
"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""


from django.db import models

from ESSArch_Core.fields import JSONField


class extensionPackage(models.Model):
    id = models.AutoField(primary_key=True)
    allElements = JSONField(null=True)
    existingElements = JSONField(null=True)
    allAttributes = JSONField(null=True)

    prefix = models.CharField(max_length=20)
    schemaURL = models.URLField()
    targetNamespace = models.CharField(max_length=255)
    nsmap = JSONField(default={})


class templatePackage(models.Model):
    existingElements = JSONField(null=True)
    # treeData = JSONField(null=True)
    allElements = JSONField(null=True)
    structure = JSONField(default=[])
    # isTreeCreated = models.BooleanField(default=True)
    name = models.CharField(max_length=255, primary_key=True)
    root_element = models.CharField(max_length=55, default='')
    extensions = models.ManyToManyField(extensionPackage)

    prefix = models.CharField(max_length=20)
    schemaURL = models.URLField()
    targetNamespace = models.CharField(max_length=255)
    nsmap = JSONField(default={})
    # generated = models.BooleanField(default=False)
    # creator         = models.CharField( max_length = 255 )
#     archivist_organization  = models.CharField( max_length = 255 )
#     label                   = models.CharField( max_length = 255 )
# #    startdate               = models.CharField( max_length = 255 )
# #    enddate                 = models.CharField( max_length = 255 )
#     createdate              = models.CharField( max_length = 255 )
#     iptype                  = models.CharField( max_length = 255 )
#     uuid                    = models.CharField( max_length = 255 )
#     directory               = models.CharField( max_length = 255 )
#     site_profile            = models.CharField( max_length = 255 )
#     state                   = models.CharField( max_length = 255 )
#     zone                    = models.CharField( max_length = 70 )
#     progress                = models.IntegerField()
    # class Meta:
    #     permissions = (
    #         ("Can_view_ip_menu", "Can_view_ip_menu"),
    #     )

ESSArch_Core/essxml/ProfileMaker/templates/templateMaker/add.html
<!doctype html>
<html>
    <head>
      <title>TemplateMaker</title>
    </head>
    <body>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
      </form>
    </body>
</html>

<!-- <!doctype html>
<html ng-app="add" ng-controller="MainController as vm">
    <head>
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/bower_components/bootstrap/dist/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/scripts/style.css">

        Angular Scripts
        <script src="/static/templateMaker/bower_components/api-check/dist/api-check.js"></script>
        <script src="/static/templateMaker/bower_components/angular/angular.js"></script>
        <script src="/static/templateMaker/bower_components/angular-formly/dist/formly.js"></script>
        <script src="/static/templateMaker/bower_components/angular-formly-templates-bootstrap/dist/angular-formly-templates-bootstrap.js"></script>

        <script src="/static/templateMaker/scripts/addApp.js"></script>
        <title>TemplateMaker</title>
    </head>
    <body>
      <form ng-submit="vm.onSubmit()" name="vm.form">
        {% csrf_token %}
        <formly-form model="vm.model" fields="vm.fields" form="vm.form" options="vm.options">
            <input type="submit" value="Submit">
        </formly-form>
        {{ form }}
        <tr><th><label for="id_template_name">Template name:</label></th><td><input id="id_template_name" maxlength="50" name="template_name" type="text" required /></td></tr>
<tr><th><label for="id_namespace_prefix">Namespace prefix:</label></th><td><input id="id_namespace_prefix" maxlength="20" name="namespace_prefix" type="text" required /></td></tr>
<tr><th><label for="id_root_element">Root element:</label></th><td><input id="id_root_element" maxlength="55" name="root_element" type="text" required /></td></tr>
<tr><th><label for="id_file">File:</label></th><td><input id="id_file" name="file" type="file" required /></td></tr>
<tr><th><label for="id_file2">File2:</label></th><td><input id="id_file2" name="file2" type="file" required /></td></tr>
        <input type="submit" value="Submit" ng-click="vm.onSubmit()">
      </form>
    </body>
</html> -->

ESSArch_Core/essxml/ProfileMaker/templates/templateMaker/create.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load staticfiles %}

{% block breadcrumbs %}
{% endblock %}

{% block content %}

<div style="margin:20px">

<H1>Submit information package <i>({{ ip.label }})</i> from <i>({{ ip.archivist_organization }})</i></H1><p>
<p><i>Please fill in the fields or use prefilled data   (* indicates mandatory field)</i></p><br/>

<form action="someAction" method="post">
	{% csrf_token %}

	<table id="result_list">
		<thead> </thead>
		<tbody>
			<H3>The receiver of the IP</H3><p>
		    <tr>
		    	<td>Receiver</td>
		    	<td>{{ form.preservation_organization_receiver }}</td>
		    	<td>{{ form.preservation_organization_receiver.errors }}</td>
		    </tr>
	    </tbody>
	</table>
	<br/>

	{% if sendemail  %}
	<table id="result_list2">
		<tbody>
			<H3>The receiver of the submit description</H3><p>
			{% for field in form %}
		        <div class="fieldWrapper">
				{% if field.label != "Receiver" %}
		            <tr><td>{{ field.label_tag }}</td><td>{{ field }}</td><td>{{ field.errors }}</td></tr>
		        </div>
		       {% endif %}
		    {% endfor %}
		</tbody>
	</table>
	<br/>
	{% endif %}

	<input type="submit" value="Submit" />
</form>
</div>

{% endblock %}

ESSArch_Core/essxml/ProfileMaker/templates/templateMaker/edit.html
<!doctype html>
<html ng-app="formlyApp" ng-controller="MainController as vm">
    <head>
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/bower_components/bootstrap/dist/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/bower_components/angular-tree-control/css/tree-control.css">
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/bower_components/angular-tree-control/css/tree-control-attribute.css">
        <link rel="stylesheet" type="text/css" href="/static/templateMaker/scripts/style.css">
        <style>
.nav, .pagination, .carousel, .panel-title a { cursor: pointer; }
        </style>

        <!--Angular Scripts -->
        <script src="/static/templateMaker/bower_components/api-check/dist/api-check.js"></script>
        <script src="/static/templateMaker/bower_components/angular/angular.js"></script>
        <script src="/static/templateMaker/bower_components/angular-formly/dist/formly.js"></script>
        <script src="/static/templateMaker/bower_components/angular-formly-templates-bootstrap/dist/angular-formly-templates-bootstrap.js"></script>
        <script src="/static/templateMaker/bower_components/angular-tree-control/angular-tree-control.js"></script>
        <!--Django-->
        <script type="text/javascript">
           var templateName = "{{templateName}}";
        </script>
        <!--App -->
        <script src="/static/templateMaker/scripts/app.js"></script>
        <!--Controllers-->
        <script src="/static/templateMaker/scripts/MainController.js"></script>

    </head>
    <body>

      <!-- <div id="tree" ng-repeat="node in vm.treeElements">
        <div id="root" onClick="">
          <div class="treerow"><p>Mets</p>
            <div class="children" ng-repeat="node in node.Children">
              <div class="treerow">
                <p>{% verbatim %}{{node.name}}{% endverbatim %}</p>
                <div class="children">
                </div>
              </div>
              <div class="treerow">
                <p>{% verbatim %}{{node.name}}{% endverbatim %}</p>
                <div class="children">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> -->

    <treecontrol class="tree-classic"
        tree-model="treeElements"
        options="treeOptions"
        on-selection="showSelected(node.key, selected)"
        selected-node="node1"
        expanded-nodes="expandedNodes"
        style="float:left;">
        <span class="{% verbatim %}{{node.templateOnly}}{% endverbatim %}">element: {% verbatim %}{{node.name}}{% endverbatim %}</span>
    </treecontrol>

    <formly-form model="vm.floatingmodel" fields="vm.floatingfields" form="vm.floatingform" class="floatingForm" ng-show="vm.floatingVisable">
        {% csrf_token %}
        <button type="button" class="btn btn-primary" ng-click="vm.saveAttribute()" ng-disabled="vm.floatingform.$invalid">Add Attribute</button>
        <button type="button" class="btn btn-danger" ng-click="vm.closeFloatingForm()">Cancel</button>
        <treecontrol class="tree-classic"
            tree-model="allAttributes"
            options="treeOptions"
            on-selection="addAttribute(node.data, $parentNode)"
            selected-node="node1"
            expanded-nodes="expandedNodes"
            style="float:left;">
            <span class="{% verbatim %}{{node.templateOnly}}{% endverbatim %}">element: {% verbatim %}{{node.name}}{% endverbatim %}</span>
        </treecontrol>
    </formly-form>

    <formly-form model="vm.floatingElementmodel" fields="vm.floatingElementfields" form="vm.floatingElementform" class="floatingForm" ng-show="vm.floatingElementVisable">
        {% csrf_token %}
        <button type="button" class="btn btn-primary" ng-click="vm.saveElement()" ng-disabled="vm.floatingElementform.$invalid">Add Element</button>
        <treecontrol class="tree-classic"
            tree-model="allElementsAvailable"
            options="treeOptions"
            on-selection="addEl(node.data)"
            selected-node="node1"
            expanded-nodes="expandedNodes"
            style="float:left;">
            <span class="{% verbatim %}{{node.templateOnly}}{% endverbatim %}">element: {% verbatim %}{{node.name}}{% endverbatim %}</span>
        </treecontrol>
    </formly-form>

    <div class="container col-md-4">
        <form onsubmit="return false;">
            {% csrf_token %}
            <input type="hidden" name="uuid" value="{% verbatim %}{{vm.uuid}}{% endverbatim %}"/>
            <input type="hidden" name="schemaName" value="{% verbatim %}{{vm.schemaName}}{% endverbatim %}"/>
            <h2>{% verbatim %}{{vm.title}}{% endverbatim %}</h2>
            <h3>Empty, non-required fields won't be used in the template</h3>
            <h3>Min: {% verbatim %}{{vm.min}}{% endverbatim %} Max: {% verbatim %}{{vm.max}}{% endverbatim %}</h3>
            <formly-form model="vm.model" fields="vm.fields" form="vm.form">
                <p ng-show="vm.containsFilesText">Contains Files</p>
                <button type="button" class="btn btn-primary" ng-click="vm.addAttribute()" ng-show="vm.anyAttribute">Add Attribute</button>
                <button type="button" class="btn btn-primary" ng-click="vm.submitForm()" ng-disabled="vm.form.$invalid">Submit</button>
                <button type="button" class="btn btn-danger" ng-show="vm.canDelete" ng-click="vm.removeChild()">Delete</button>
                <button type="button" class="btn btn-primary" ng-click="vm.containsFiles()">Toggle Contains Files</button>
            </formly-form>
            <!-- <h3>Available children</h3> -->
            <div>
                <h3 ng-if="vm.possibleChildren.length > 0">PossibleChildren</h3>
                <div ng-repeat="child in vm.possibleChildren track by $index" class="children">
                    <p>
                        {% verbatim %}{{child}}{% endverbatim %}
                    </p>
                    <button type="button" class="btn btn-success" ng-click="vm.addChild(child)">Add</button>
                    <!-- <span ng-click="vm.addChild(child)">{% verbatim %}{{child.name}}{% endverbatim %}
                    </span> -->
                </div>
                <button type="button" class="btn btn-success" ng-click="vm.addElement()" ng-show="vm.anyElement">Add Element</button>
            </div>
        </form>
    </div>

    </body>
</html>